-- Populate 'user' table
INSERT INTO IMPERIUM_CASH.USER (NAME, EMAIL, PASSWORD) VALUES ('Hélio Márcio Filho', 'heliommsfilho@gmail.com', '$2a$10$M2dh1tG1KEa8BWZ5WwWq1.MccU8Jvxpuu6iNAdFjwl8i41zz3X0g6');

-- Populate 'country' table
INSERT INTO IMPERIUM_CASH.COUNTRY (CODE, NAME) VALUES ('US', 'United States Of America');
INSERT INTO IMPERIUM_CASH.COUNTRY (CODE, NAME) VALUES ('BR', 'Brasil');
INSERT INTO IMPERIUM_CASH.COUNTRY (CODE, NAME) VALUES ('PT', 'Portugal');

-- Populate 'currency' table
INSERT INTO IMPERIUM_CASH.CURRENCY (NAME, CODE, SYMBOL) VALUES ('United States Dollar', 'USD', '$');
INSERT INTO IMPERIUM_CASH.CURRENCY (NAME, CODE, SYMBOL) VALUES ('Euro', 'EUR', '€');
INSERT INTO IMPERIUM_CASH.CURRENCY (NAME, CODE, SYMBOL) VALUES ('Real', 'BRL', 'R$');

-- Populate 'currency_format' table
INSERT INTO IMPERIUM_CASH.CURRENCY_FORMAT (PATTERN, EXAMPLE_POSITIVE, EXAMPLE_NEGATIVE) VALUES ('$_###,##0.00', '$_123,456.78', '$_-123,456.78');
INSERT INTO IMPERIUM_CASH.CURRENCY_FORMAT (PATTERN, EXAMPLE_POSITIVE, EXAMPLE_NEGATIVE) VALUES ('###,##0.00_$', '123,456.78_$', '-123,456.78_$');
INSERT INTO IMPERIUM_CASH.CURRENCY_FORMAT (PATTERN, EXAMPLE_POSITIVE, EXAMPLE_NEGATIVE) VALUES ('@_###.##0,00', '@_123.456,78', '@_-123.456,78');
INSERT INTO IMPERIUM_CASH.CURRENCY_FORMAT (PATTERN, EXAMPLE_POSITIVE, EXAMPLE_NEGATIVE) VALUES ('###,##0.00_@', '123,456.78_@', '-123,456.78_@');

-- Populate 'date_format' table
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('dd/MM/yyyy', '20/11/2020');
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('MM/dd/yyyy', '11/20/2020');
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('yyyy/MM/dd', '2020/11/20');
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('dd-MM-yyyy', '20-11-2020');
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('MM-dd-yyyy', '11-20-2020');
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('yyyy-MM-dd', '2020-11-20');
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('dd.MM.yyy', '20.11.2020');
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('MM.dd.yyyy', '11.20.2020');
INSERT INTO IMPERIUM_CASH.DATE_FORMAT (PATTERN, EXAMPLE) VALUES ('yyyy.MM.dd', '2020.11.20');
