-- Populate 'currency' table
INSERT INTO IMPERIUM_CASH.CURRENCY (NAME, CODE, SYMBOL) VALUES ('United States Dollar', 'USD', '$');
INSERT INTO IMPERIUM_CASH.CURRENCY (NAME, CODE, SYMBOL) VALUES ('Euro', 'EUR', '€');
INSERT INTO IMPERIUM_CASH.CURRENCY (NAME, CODE, SYMBOL) VALUES ('Real Brasileiro', 'BRL', 'R$');