-- Clean database
DROP SCHEMA IF EXISTS IMPERIUM_CASH CASCADE;
CREATE SCHEMA IMPERIUM_CASH;

---- System-wide tables ----
-- Create 'user'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.USER_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.USER
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.USER_ID_SEQ') CONSTRAINT USER_PK PRIMARY KEY,
    TENANT_UUID CHAR(36) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL
);

CREATE UNIQUE INDEX USER_TENTANT_UUID_UINDEX ON IMPERIUM_CASH.USER (TENANT_UUID);
CREATE UNIQUE INDEX USER_EMAIL_UINDEX ON IMPERIUM_CASH.USER (EMAIL);

-- Create 'currency'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.CURRENCY_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.CURRENCY
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.CURRENCY_ID_SEQ') CONSTRAINT CURRENCY_PK PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CODE CHAR(3) NOT NULL,
    SYMBOL VARCHAR(10) NOT NULL
);

CREATE UNIQUE INDEX CURRENCY_NAME_UINDEX ON IMPERIUM_CASH.CURRENCY (NAME);
CREATE UNIQUE INDEX CURRENCY_CODE_UINDEX ON IMPERIUM_CASH.CURRENCY (CODE);
CREATE UNIQUE INDEX CURRENCY_SYMBOL_UINDEX ON IMPERIUM_CASH.CURRENCY (SYMBOL);

-- Create 'currency_format'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.CURRENCY_FORMAT_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.CURRENCY_FORMAT
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.CURRENCY_FORMAT_ID_SEQ') CONSTRAINT CURRENCY_FORMAT_PK PRIMARY KEY,
    PATTERN VARCHAR(10) NOT NULL,
    EXAMPLE_POSITIVE VARCHAR(10) NOT NULL,
    EXAMPLE_NEGATIVE VARCHAR(10) NOT NULL
);

CREATE UNIQUE INDEX CURRENCY_FORMAT_PATTERN_UINDEX ON IMPERIUM_CASH.CURRENCY_FORMAT (PATTERN);

-- Create 'date_format'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.DATE_FORMAT_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.DATE_FORMAT
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.DATE_FORMAT_ID_SEQ') CONSTRAINT DATE_FORMAT_PK PRIMARY KEY,
    PATTERN VARCHAR(10) NOT NULL,
    EXAMPLE VARCHAR(10) NOT NULL
);

CREATE UNIQUE INDEX DATE_FORMAT_PATTERN_UINDEX ON IMPERIUM_CASH.DATE_FORMAT (PATTERN);

-- Create 'account_type'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.ACCOUNT_TYPE_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.ACCOUNT_TYPE
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.ACCOUNT_TYPE_ID_SEQ') CONSTRAINT ACCOUNT_TYPE_PK PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX ACCOUNT_TYPE_NAME_UINDEX ON IMPERIUM_CASH.ACCOUNT_TYPE (NAME);
---- System-wide tables ----

---- Userspace tables ----