-- Clean database
DROP SCHEMA IF EXISTS IMPERIUM_CASH CASCADE;
CREATE SCHEMA IMPERIUM_CASH;

---- System-wide tables ----
-- Create 'user'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.USER_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.USER
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.USER_ID_SEQ') CONSTRAINT USER_PK PRIMARY KEY,
    TENANT_UUID CHAR(36) NOT NULL,
    NAME VARCHAR(50),
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL
);

CREATE UNIQUE INDEX USER_EMAIL_UINDEX ON IMPERIUM_CASH.USER (EMAIL);
CREATE UNIQUE INDEX USER_TENANT_UUID_UINDEX ON IMPERIUM_CASH.USER (TENANT_UUID);

-- Create 'country'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.COUNTRY_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.COUNTRY
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.COUNTRY_ID_SEQ') CONSTRAINT COUNTRY_PK PRIMARY KEY,
    CODE CHAR(2) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX COUNTRY_CODE_UINDEX ON IMPERIUM_CASH.COUNTRY (CODE);

-- Create 'currency'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.CURRENCY_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.CURRENCY
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.CURRENCY_ID_SEQ') CONSTRAINT CURRENCY_PK PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CODE CHAR(3) NOT NULL,
    SYMBOL VARCHAR(10) NOT NULL
);

CREATE UNIQUE INDEX CURRENCY_NAME_UINDEX ON IMPERIUM_CASH.CURRENCY (NAME);
CREATE UNIQUE INDEX CURRENCY_CODE_UINDEX ON IMPERIUM_CASH.CURRENCY (CODE);
CREATE UNIQUE INDEX CURRENCY_SYMBOL_UINDEX ON IMPERIUM_CASH.CURRENCY (SYMBOL);

-- Create 'currency_format'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.CURRENCY_FORMAT_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.CURRENCY_FORMAT
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.CURRENCY_FORMAT_ID_SEQ') CONSTRAINT CURRENCY_FORMAT_PK PRIMARY KEY,
    PATTERN VARCHAR(20) NOT NULL,
    EXAMPLE_POSITIVE VARCHAR(20) NOT NULL,
    EXAMPLE_NEGATIVE VARCHAR(20) NOT NULL
);

CREATE UNIQUE INDEX CURRENCY_FORMAT_PATTERN_UINDEX ON IMPERIUM_CASH.CURRENCY_FORMAT (PATTERN);

-- Create 'date_format'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.DATE_FORMAT_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.DATE_FORMAT
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.DATE_FORMAT_ID_SEQ') CONSTRAINT DATE_FORMAT_PK PRIMARY KEY,
    PATTERN VARCHAR(10) NOT NULL,
    EXAMPLE VARCHAR(10) NOT NULL
);

CREATE UNIQUE INDEX DATE_FORMAT_PATTERN_UINDEX ON IMPERIUM_CASH.DATE_FORMAT (PATTERN);

-- Create 'bank_logo'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.BANK_LOGO_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.BANK_LOGO(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.BANK_LOGO_ID_SEQ') CONSTRAINT BANK_LOGO_PK PRIMARY KEY,
    BANK_NAME VARCHAR(50) NOT NULL,
    IMAGE_DATA TEXT NOT NULL
);

CREATE UNIQUE INDEX BANK_LOGO_BANK_NAME_UINDEX ON IMPERIUM_CASH.BANK_LOGO (BANK_NAME);

-- Create 'account_type'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.ACCOUNT_TYPE_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.ACCOUNT_TYPE
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.ACCOUNT_TYPE_ID_SEQ') CONSTRAINT ACCOUNT_TYPE_PK PRIMARY KEY,
    DEFAULT_BANK_LOGO_ID BIGINT CONSTRAINT ACCOUNT_TYPE_BANK_LOGO__DEFAULT_BANK_LOGO_ID_FK REFERENCES IMPERIUM_CASH.BANK_LOGO (ID) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX ACCOUNT_TYPE_NAME_UINDEX ON IMPERIUM_CASH.ACCOUNT_TYPE (NAME);
---- System-wide tables ----

---- Userspace tables ----