-- Clean database
DROP SCHEMA IF EXISTS IMPERIUM_CASH CASCADE;
CREATE SCHEMA IMPERIUM_CASH;

---- System-wide tables ----
-- Create 'user'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.USER_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.USER
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.USER_ID_SEQ') CONSTRAINT USER_PK PRIMARY KEY,
    TENANT_UUID CHAR(36) NOT NULL,
    NAME VARCHAR(50),
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    CREATION_DATE TIMESTAMP(6) NOT NULL,
    LAST_UPDATE TIMESTAMP(6) NOT NULL,

    UNIQUE(EMAIL),
    UNIQUE(TENANT_UUID)
);

CREATE UNIQUE INDEX USER_EMAIL_UINDEX ON IMPERIUM_CASH.USER (EMAIL);
CREATE UNIQUE INDEX USER_TENANT_UUID_UINDEX ON IMPERIUM_CASH.USER (TENANT_UUID);

-- Create 'country'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.COUNTRY_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.COUNTRY
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.COUNTRY_ID_SEQ') CONSTRAINT COUNTRY_PK PRIMARY KEY,
    CODE CHAR(2) NOT NULL,
    NAME VARCHAR(50) NOT NULL,

    UNIQUE(CODE)
);

-- Create 'currency'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.CURRENCY_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.CURRENCY
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.CURRENCY_ID_SEQ') CONSTRAINT CURRENCY_PK PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CODE CHAR(3) NOT NULL,
    SYMBOL VARCHAR(10) NOT NULL,

    UNIQUE(NAME),
    UNIQUE(CODE),
    UNIQUE(SYMBOL)
);

-- Create 'currency_format'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.CURRENCY_FORMAT_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.CURRENCY_FORMAT
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.CURRENCY_FORMAT_ID_SEQ') CONSTRAINT CURRENCY_FORMAT_PK PRIMARY KEY,
    PATTERN VARCHAR(20) NOT NULL,
    EXAMPLE_POSITIVE VARCHAR(20) NOT NULL,
    EXAMPLE_NEGATIVE VARCHAR(20) NOT NULL,

    UNIQUE(PATTERN)
);

-- Create 'date_format'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.DATE_FORMAT_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.DATE_FORMAT
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.DATE_FORMAT_ID_SEQ') CONSTRAINT DATE_FORMAT_PK PRIMARY KEY,
    PATTERN VARCHAR(10) NOT NULL,
    EXAMPLE VARCHAR(10) NOT NULL,

    UNIQUE(PATTERN)
);

-- Create 'bank_logo'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.BANK_LOGO_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.BANK_LOGO(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.BANK_LOGO_ID_SEQ') CONSTRAINT BANK_LOGO_PK PRIMARY KEY,
    BANK_NAME VARCHAR(50) NOT NULL,
    IMAGE_DATA TEXT NOT NULL,

    UNIQUE(BANK_NAME)
);

-- Create 'account_type'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.ACCOUNT_TYPE_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.ACCOUNT_TYPE
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.ACCOUNT_TYPE_ID_SEQ') CONSTRAINT ACCOUNT_TYPE_PK PRIMARY KEY,
    BANK_LOGO_ID BIGINT CONSTRAINT ACCOUNT_TYPE_BANK_LOGO__BANK_LOGO_ID_FK REFERENCES IMPERIUM_CASH.BANK_LOGO (ID) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,

    UNIQUE(NAME)
);

---- System-wide tables ----

---- Userspace tables ----
-- Create 'budget'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.BUDGET_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.BUDGET
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.BUDGET_ID_SEQ') CONSTRAINT BUDGET_PK PRIMARY KEY,
    UUID CHAR(36) NOT NULL,
    USER_ID BIGINT CONSTRAINT BUDGET_USER__USER_ID_FK REFERENCES IMPERIUM_CASH.USER (ID) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(250),
    CURRENCY_ID BIGINT CONSTRAINT BUDGET_CURRENCY__CURRENCY_ID_FK REFERENCES IMPERIUM_CASH.CURRENCY (ID) NOT NULL,
    CURRENCY_FORMAT_ID BIGINT CONSTRAINT BUDGET_CURRENCY_FORMAT__CURRENCY_FORMAT_ID_FK REFERENCES IMPERIUM_CASH.CURRENCY_FORMAT (ID) NOT NULL,
    DATE_FORMAT_ID BIGINT CONSTRAINT BUDGET_DATE_FORMAT__DATE_FORMAT_ID_FK REFERENCES IMPERIUM_CASH.DATE_FORMAT (ID) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATION_DATE TIMESTAMP(6) NOT NULL,
    LAST_UPDATE TIMESTAMP(6) NOT NULL,

    UNIQUE(NAME)
);

-- Create 'payee'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.PAYEE_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.PAYEE
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.PAYEE_ID_SEQ') CONSTRAINT PAYEE_PK PRIMARY KEY,
    BUDGET_ID BIGINT CONSTRAINT PAYEE_BUDGET__BUDGET_ID_FK REFERENCES IMPERIUM_CASH.BUDGET (ID) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DISABLED BOOLEAN,
    CREATION_DATE TIMESTAMP(6) NOT NULL,
    LAST_UPDATE TIMESTAMP(6) NOT NULL,

    UNIQUE (BUDGET_ID, NAME)
);

-- Create 'group_category'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.GROUP_CATEGORY_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.GROUP_CATEGORY
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.GROUP_CATEGORY_ID_SEQ') CONSTRAINT GROUP_CATEGORY_PK PRIMARY KEY,
    BUDGET_ID BIGINT CONSTRAINT GROUP_CATEGORY_BUDGET__BUDGET_ID_FK REFERENCES IMPERIUM_CASH.BUDGET (ID) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DISABLED BOOLEAN,
    CREATION_DATE TIMESTAMP(6) NOT NULL,
    LAST_UPDATE TIMESTAMP(6) NOT NULL,

    UNIQUE (BUDGET_ID, NAME)
);

-- Create 'category'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.CATEGORY_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.CATEGORY
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.CATEGORY_ID_SEQ') CONSTRAINT CATEGORY_PK PRIMARY KEY,
    GROUP_CATEGORY_ID BIGINT CONSTRAINT CATEGORY_GROUP_CATEGORY__GROUP_CATEGORY_ID_FK REFERENCES IMPERIUM_CASH.GROUP_CATEGORY (ID) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DISABLED BOOLEAN,
    CREATION_DATE TIMESTAMP(6) NOT NULL,
    LAST_UPDATE TIMESTAMP(6) NOT NULL,

    UNIQUE (GROUP_CATEGORY_ID, NAME)
);


-- Create 'account'
CREATE SEQUENCE IF NOT EXISTS IMPERIUM_CASH.ACCOUNT_ID_SEQ INCREMENT 1 START 1;

CREATE TABLE IMPERIUM_CASH.ACCOUNT
(
    ID BIGINT DEFAULT NEXTVAL('IMPERIUM_CASH.ACCOUNT_ID_SEQ') CONSTRAINT ACCOUNT_PK PRIMARY KEY,
    BUDGET_ID BIGINT CONSTRAINT ACCOUNT_BUDGET__BUDGET_ID_FK REFERENCES IMPERIUM_CASH.BUDGET (ID) NOT NULL,
    ACCOUNT_TYPE_ID BIGINT CONSTRAINT ACCOUNT_ACCOUNT_TYPE__ACCOUNT_TYPE_ID_FK REFERENCES IMPERIUM_CASH.ACCOUNT_TYPE (ID) NOT NULL,
    BANK_LOGO_ID BIGINT CONSTRAINT ACCOUNT_BANK_LOGO__BANK_LOGO_ID_FK REFERENCES IMPERIUM_CASH.BANK_LOGO (ID) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DISABLED BOOLEAN,
    CREATION_DATE TIMESTAMP(6) NOT NULL,
    LAST_UPDATE TIMESTAMP(6) NOT NULL,

    UNIQUE (BUDGET_ID, NAME)
);
